using Pkg; Pkg.activate("./tutorials")
using PlantModules
using ModelingToolkit, OrdinaryDiffEq, Plots
using ModelingToolkit: t_nounits as t, D_nounits as d

function mini_hydraulics(; name, D)
    @parameters (
        T = 298.15, [description = "Temperature"],
        ϕ_D = 3.0, [description = "extensibility"],
        Γ = 0.3, [description = "critical pressure"],
    )
    @variables (
        Ψ(t), [description = "Total water potential"],
        P(t), [description = "Hydrostatic potential"],
        W(t), [description = "Water content"],
        D(t) = D, [description = "Dimension of compartment"],
        ΣF(t), [description = "Net incoming water flux"],
        
        ΔP(t), [description = "Change in hydrostatic potential"],
        ΔW(t), [description = "Change in water content"],
        ΔD(t), [description = "Change in dimensions of compartment"],
    )

    eqs = [
        Ψ ~ P,
        ΔW ~ ΣF,
        W ~ D,
        ΔD ~ D * ϕ_D * (P - Γ),

        d(W) ~ ΔW,
        d(D) ~ ΔD,
    ]
    return ODESystem(eqs, t; name)
end

function mini_connection(; name, K)
    @parameters (
        K = K, [description = "Hydraulic conductivity of connection"],
    )
    @variables (
        F(t), [description = "Water flux from compartment 1 to compartment 2"],
        Ψ_1(t), [description = "Total water potential of compartment 1"],
        Ψ_2(t), [description = "Total water potential of compartment 2"],
    )

    eqs = [
        F ~ K * (Ψ_1 - Ψ_2)
    ]
    return ODESystem(eqs, t; name)
end

# Create compartment instances #


@named stem = mini_hydraulics(D = 3.0)
@named leaf = mini_hydraulics(D = 0.5)

@named stem_leaf = mini_connection(K = 600)
@named leaf_stem = mini_connection(K = 600)

# define connections #

connections = [
    stem_leaf.Ψ_1 ~ stem.Ψ,
    stem_leaf.Ψ_2 ~ leaf.Ψ,
    stem.ΣF ~ - stem_leaf.F,

    leaf_stem.Ψ_1 ~ leaf.Ψ,
    leaf_stem.Ψ_2 ~ stem.Ψ,
    leaf.ΣF ~ - leaf_stem.F,
]

# build model #

## model definition
plant = compose(ODESystem(connections, t, name = :plant), stem, leaf, stem_leaf, leaf_stem)
plant_simp = structural_simplify(plant)

# full_equations(plant_simp)

## initial values

u0 = [
    stem.P => 0.1,
    stem.W => volume(stemvol, stem.D) * stem.ρ_w,

    leaf.P => 0.1,
    leaf.W => volume(leafvol, leaf.D) * leaf.ρ_w,
]

### Adding initial values for dummy derivatives generated by MTK (see https://docs.sciml.ai/ModelingToolkit/stable/basics/FAQ/#ERROR:-ArgumentError:-SymbolicUtils.BasicSymbolic{Real}[x%CB%8Dt(t)]-are-missing-from-the-variable-map.)
u0_req = ModelingToolkit.missing_variable_defaults(plant_simp) # generates zero initial value for ALL initial states
u0_ext = union(u0, u0_req) # add actual values of non-dummy initial states 
u0_full = unique(x -> x[1], u0_ext) # remove duplicates

## define and solve problem
prob = ODEProblem(plant_simp, u0_full, (0.0, 24.0*31))
sol = solve(prob)

plot(sol, idxs = [leaf_stem.F, stem_leaf.F])